


import { Inter } from "next/font/google";
import "./globals.css";
import CustomNavbar from "@/components/CustomNavbar";
import Footer from "@/components/Footer";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
const inter = Inter({ subsets: ["latin"] });

// This comment becuase i want every page component show it's own metadata

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        {
          // <h1>This is Header Part </h1>
        }
        <ToastContainer />
        <CustomNavbar />

        {children}
        {
          // Children represents pages 
        }
        {
          // <h1>This is Footer Part</h1>
        }

        <Footer />
      </body>
    </html>
  );
}
