import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>This is Header Part </h1>
        {children}
        {
          // Children represents pages 
        }
        <h1>This is Footer Part</h1>
      </body>
    </html>
  );
}
